services:
  - type: web
    name: dashboard-react
    env: static
    staticPublishPath: dashboard-react/dist
    buildCommand: npm install && npm run build
    envVars:
      - key: VITE_API_URL
        value: https://ml-service.onrender.com
    autoDeploy: true

  - type: web
    name: app-trainer-java
    env: docker
    dockerfilePath: app-trainer-java-web/app-trainer-java-web/Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8081
      - key: JWT_SECRET_KEY
        sync: false
      - key: DB_URL
        fromDatabase:
          name: app-trainer-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: app-trainer-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: app-trainer-db
          property: password
      - key: ML_SERVICE_URL
        value: https://ml-service.onrender.com

  - type: web
    name: ml-service
    env: docker
    dockerfilePath: ml-service/Dockerfile
    autoDeploy: true
    healthCheckPath: /ml/health
    envVars:
      - key: PORT
        value: 8001
      - key: JWT_SECRET_KEY
        sync: false

databases:
  - name: app-trainer-db